<template>
  <svg
    id="svg5"
    width="300"
    height="300"
    viewBox="0 0 264.58333 264.58334"
    version="1.1"
  >
    <defs
      id="defs2"
    >
      <filter
        id="filter18088"
        style="color-interpolation-filters:sRGB;"
        inkscape:label="Drop Shadow"
        x="-0.084661669"
        y="-0.088588676"
        width="1.2184573"
        height="1.2285904"
      >
        <feFlood
          id="feFlood18078"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
        />
        <feComposite
          id="feComposite18080"
          in="flood"
          in2="SourceGraphic"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur18082"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset18084"
          dx="2.5"
          dy="2.5"
          result="offset"
        />
        <feComposite
          id="feComposite18086"
          in="offset"
          in2="SourceGraphic"
          operator="atop"
          result="fbSourceGraphic"
        />
        <feColorMatrix
          id="feColorMatrix18948"
          result="fbSourceGraphicAlpha"
          in="fbSourceGraphic"
          values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
        />
        <feFlood
          id="feFlood18950"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
          in="fbSourceGraphic"
        />
        <feComposite
          id="feComposite18952"
          in2="fbSourceGraphic"
          in="flood"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur18954"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset18956"
          dx="1.4"
          dy="1.4"
          result="offset"
        />
        <feComposite
          id="feComposite18958"
          in2="fbSourceGraphic"
          in="offset"
          operator="atop"
          result="composite2"
        />
      </filter>
      <filter
        id="filter19078"
        style="color-interpolation-filters:sRGB;"
        inkscape:label="Drop Shadow"
        x="-0.075546215"
        y="-0.079998996"
        width="1.18257"
        height="1.1933309"
      >
        <feFlood
          id="feFlood19068"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
        />
        <feComposite
          id="feComposite19070"
          in="flood"
          in2="SourceGraphic"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur19072"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset19074"
          dx="1.4"
          dy="1.4"
          result="offset"
        />
        <feComposite
          id="feComposite19076"
          in="offset"
          in2="SourceGraphic"
          operator="atop"
          result="fbSourceGraphic"
        />
        <feColorMatrix
          id="feColorMatrix19098"
          result="fbSourceGraphicAlpha"
          in="fbSourceGraphic"
          values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
        />
        <feFlood
          id="feFlood19100"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
          in="fbSourceGraphic"
        />
        <feComposite
          id="feComposite19102"
          in2="fbSourceGraphic"
          in="flood"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur19104"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset19106"
          dx="1.4"
          dy="1.4"
          result="offset"
        />
        <feComposite
          id="feComposite19108"
          in2="fbSourceGraphic"
          in="offset"
          operator="atop"
          result="composite2"
        />
      </filter>
      <filter
        id="filter22086"
        style="color-interpolation-filters:sRGB;"
        inkscape:label="Drop Shadow"
        x="-0.098191319"
        y="-0.10274589"
        width="1.2372957"
        height="1.2483026"
      >
        <feFlood
          id="feFlood22076"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
        />
        <feComposite
          id="feComposite22078"
          in="flood"
          in2="SourceGraphic"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur22080"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset22082"
          dx="1.4"
          dy="1.4"
          result="offset"
        />
        <feComposite
          id="feComposite22084"
          in="offset"
          in2="SourceGraphic"
          operator="atop"
          result="fbSourceGraphic"
        />
        <feColorMatrix
          id="feColorMatrix22106"
          result="fbSourceGraphicAlpha"
          in="fbSourceGraphic"
          values="0 0 0 -1 0 0 0 0 -1 0 0 0 0 -1 0 0 0 0 1 0"
        />
        <feFlood
          id="feFlood22108"
          flood-opacity="0.8"
          flood-color="rgb(0,0,0)"
          result="flood"
          in="fbSourceGraphic"
        />
        <feComposite
          id="feComposite22110"
          in2="fbSourceGraphic"
          in="flood"
          operator="out"
          result="composite1"
        />
        <feGaussianBlur
          id="feGaussianBlur22112"
          in="composite1"
          stdDeviation="1.4"
          result="blur"
        />
        <feOffset
          id="feOffset22114"
          dx="1.4"
          dy="1.4"
          result="offset"
        />
        <feComposite
          id="feComposite22116"
          in2="fbSourceGraphic"
          in="offset"
          operator="atop"
          result="composite2"
        />
      </filter>
    </defs>
    <g
      id="layer1"
      inkscape:label="Background"
      inkscape:groupmode="layer"
    >
      <g
        id="g1170"
        inkscape:export-filename="/Users/carl/Desktop/kih2_vertical.png"
        inkscape:export-xdpi="299.99997"
        inkscape:export-ydpi="299.99997"
        transform="matrix(0,1,1,0,-3.5058593e-6,0)"
      >
        <rect
          id="rect846"
          style="fill:#004d40;fill-opacity:1;stroke:none;stroke-width:1.95177;stroke-linecap:round;stroke-linejoin:round"
          width="132.29167"
          height="264.58334"
          x="0"
          y="0"
        />
        <rect
          id="rect846-9"
          style="fill:#e9ecef;fill-opacity:1;stroke:none;stroke-width:1.95177;stroke-linecap:round;stroke-linejoin:round"
          width="132.29167"
          height="264.58334"
          x="132.29167"
          y="0"
        />
        <circle
          id="path1004"
          style="fill:#004d40;fill-opacity:1;stroke:none;stroke-width:2.21509;stroke-linecap:round;stroke-linejoin:round"
          cx="132.29167"
          cy="66.145836"
          r="66.145836"
        />
        <circle
          id="path1004-3"
          style="fill:#e9ecef;fill-opacity:1;stroke:none;stroke-width:2.21509;stroke-linecap:round;stroke-linejoin:round"
          cx="132.29167"
          cy="198.4375"
          r="66.145836"
        />
      </g>
      <text
        id="text2253"
        xml:space="preserve"
        style="font-style:normal;font-weight:normal;font-size:91.3694px;line-height:1.25;font-family:sans-serif;fill:#e9ecef;fill-opacity:1;stroke:none;stroke-width:0.264929;filter:url(#filter22086)"
        x="24.773521"
        y="166.8053"
        inkscape:export-filename="/Users/carl/Desktop/kih2_vertical.png"
        inkscape:export-xdpi="299.99997"
        inkscape:export-ydpi="299.99997"
      ><tspan
        id="tspan2251"
        sodipodi:role="line"
        style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:91.3694px;font-family:Arial;-inkscape-font-specification:Arial;fill:#e9ecef;fill-opacity:1;stroke-width:0.264929"
        x="24.773521"
        y="166.8053"
      >Ki</tspan></text>
      <text
        id="text2253-7"
        xml:space="preserve"
        style="font-style:normal;font-weight:normal;font-size:91.7222px;line-height:1.25;font-family:sans-serif;fill:#004d40;fill-opacity:1;stroke:none;stroke-width:0.264929;filter:url(#filter19078)"
        x="154.90128"
        y="167.4023"
        inkscape:export-filename="/Users/carl/Desktop/kih2_vertical.png"
        inkscape:export-xdpi="299.99997"
        inkscape:export-ydpi="299.99997"
      ><tspan
        id="tspan2251-4"
        sodipodi:role="line"
        style="font-style:normal;font-variant:normal;font-weight:normal;font-stretch:normal;font-size:91.7222px;font-family:Arial;-inkscape-font-specification:Arial;fill:#004d40;fill-opacity:1;stroke-width:0.264929"
        x="154.90128"
        y="167.4023"
      >H<tspan
        id="tspan2622"
        style="font-size:65%;baseline-shift:sub;fill:#004d40;fill-opacity:1"
      >2</tspan></tspan></text>
    </g>
    <g
      id="layer2"
      inkscape:groupmode="layer"
      inkscape:label="Text"
    />
  </svg>
</template>

<script>

export default {
  name: 'Logo',
};
</script>
